@startuml chessEngineDesignClassDiagram

skinparam linetype ortho
skinparam groupInheritance 2
left to right direction

class ChessBot {
  - MiniMaxTree processingUnit
  ---
  + ChessBot()
}

class MiniMaxTree {
  - TreeNode root
  ---
  + MiniMaxTree(Board board)
  + int alphaBeta(TreeNode node, int alpha, int beta)
}

class TreeNode {
  - int value
  - Board board
  - TreeNode parent
  - TreeNode firstChild
  - TreeNode nextSibling
  ---
  + TreeNode(Board board)
  + int getValue()
  + Board getBoard()
  + TreeNode getParent()
  + TreeNode getFirstChild()
  + TreeNode getNextSibling()
}

class Board {
  - Color playerTurn
  - int[8][8] weights
  ---
  + Board(Optional<GamePiece>[8][8] board, Color playerTurn)
  + void deserialize(String boardPath)
  + void placePiece(GamePiece piece, Coordinates coordinates)
  + void makeMove(Coordinates startCoordinates, Coordinates targetCoordinates)
  - Collection<Coordinates> getValidatePieceMove(GamePiece piece, Coordinates targetCoordinates)
  + int calculateScore(Color player)
}

class Coordinates <<record>> {
  - int xCoordinate
  - int yCoordinate
  ---
  + Coordinates(int x, int y)
}

enum Color {
  WHITE
  BLACK
}

interface GamePiece {
  ---
  + Coordinates getNextMove()
  + Color getBoard()
}

together {
  class Pawn {
    - Coordinates moves
    - Color color
  }
  class Rook {
    - Coordinates moves
    - Color color
  }
  class Bishop {
    - Coordinates moves
    - Color color
  }
  class Knight {
    - Coordinates moves
    - Color color
  }
  class Queen {
    - Coordinates moves
    - Color color
  }
  class King {
    - Coordinates moves
    - Color color
  }
}

Board -[hidden]right- GamePiece
'GamePiece -[hidden]right- Color

ChessBot    *--   MiniMaxTree
MiniMaxTree *--   TreeNode
TreeNode    *--   TreeNode
TreeNode    *--   Board
Board       *--   GamePiece

Pawn        ..|>  GamePiece
Rook        ..|>  GamePiece
Bishop      ..|>  GamePiece
Queen       ..|>  GamePiece
King        ..|>  GamePiece
Knight      ..|>  GamePiece

Color       <-    GamePiece
GamePiece   ->    Coordinates

@enduml
